# Generated by Django 2.2.4 on 2019-10-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(default='personal', max_length=50),
            preserve_default=False,
        ),
    ]
