# Generated by Django 2.2.4 on 2019-10-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
