# Generated by Django 2.2.6 on 2019-10-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_auto_20191014_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
