# Generated by Django 2.2.6 on 2019-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_pin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
