# Generated by Django 2.2.6 on 2019-10-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20191005_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pin',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pin',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
