# Generated by Django 2.2.6 on 2019-10-17 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_auto_20191006_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
