# Generated by Django 2.2.6 on 2019-10-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_pin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
