# Generated by Django 2.2.4 on 2019-09-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pin',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
