# Generated by Django 2.2.4 on 2019-09-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190904_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='user_id',
            new_name='user',
        ),
    ]
