# Generated by Django 2.2.4 on 2019-09-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190904_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='user',
            new_name='user_id',
        ),
    ]
