# Generated by Django 2.2.4 on 2019-09-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190904_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
