# Generated by Django 3.0.5 on 2020-04-17 06:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='categoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('image_url', models.ImageField(null=True, upload_to=pins.models.categoryType.upload_photo_dir)),
            ],
        ),
        migrations.CreateModel(
            name='commentStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous_comment', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqQuestionDesc', models.TextField()),
                ('faqAnswerDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('upVotes', models.PositiveSmallIntegerField(default=0)),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='startDate')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='endDate')),
                ('is_anonymous_pin', models.BooleanField(default=False)),
                ('postDate', models.DateField(blank=True, null=True, verbose_name='postDate')),
                ('lastEditDate', models.DateField(blank=True, null=True, verbose_name='lastEditDate')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_category', to='pins.categoryType')),
                ('lastPersonEdit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userStories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='upVoteStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('pinId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updotes', to='pins.pin')),
                ('upVoter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upvoted_stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(null=True, upload_to=pins.models.photo.upload_photo_dir)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='flagStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', models.BooleanField(default=False)),
                ('reportType', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('reason', models.TextField(null=True)),
                ('flagger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pinId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flaggerstory', to='pins.pin')),
            ],
        ),
        migrations.CreateModel(
            name='FlagComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', models.BooleanField(default=False)),
                ('reportType', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flaggingComment', to='pins.commentStory')),
                ('flagger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flaggerComment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentstory',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentstory', to='pins.pin'),
        ),
        migrations.AddConstraint(
            model_name='upvotestory',
            constraint=models.UniqueConstraint(fields=('pinId', 'upVoter'), name='upvoter-pin'),
        ),
        migrations.AddConstraint(
            model_name='flagstory',
            constraint=models.UniqueConstraint(fields=('pinId', 'flagger'), name='flagger-pin'),
        ),
    ]
