# Generated by Django 2.2.7 on 2019-12-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='pin',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
