# Generated by Django 2.2.7 on 2019-12-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='upVotes',
        ),
    ]
