# Generated by Django 2.2.6 on 2019-11-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='upvotestory',
            name='upvoter-pin',
        ),
    ]
