# Generated by Django 3.0.2 on 2020-01-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='endDate',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='startDate',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
