# Generated by Django 2.2.6 on 2019-10-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_pin_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='owner',
        ),
    ]
