# Generated by Django 3.0.2 on 2020-03-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200229_1342'),
        ('pins', '0002_auto_20200304_0023'),
    ]

    operations = [
    ]
