# Generated by Django 3.0.2 on 2020-03-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200223_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['id']},
        ),
    ]
