# Generated by Django 2.2.6 on 2019-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20191104_1444'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='upvotestory',
            constraint=models.UniqueConstraint(fields=('pinId', 'upVoter'), name='upvoter-pin'),
        ),
    ]
