# Generated by Django 3.0.2 on 2020-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200203_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentstory',
            name='is_anonymous_comment',
            field=models.BooleanField(default=False),
        ),
    ]
