# Generated by Django 2.2.7 on 2019-12-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20191221_2202'),
        ('pins', '0002_auto_20191228_1921'),
    ]

    operations = [
    ]
