# Generated by Django 3.0.5 on 2020-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200329_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
