# Generated by Django 3.0.2 on 2020-01-29 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200128_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='endDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='startDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
