# Generated by Django 2.2.6 on 2019-11-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20191110_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='countUpvoteFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upVotes', models.PositiveSmallIntegerField(default=0)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
                ('pinId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.pin')),
            ],
        ),
    ]
