# Generated by Django 3.0.2 on 2020-03-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200222_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='lastEditDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='pin',
            name='postDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
