# Generated by Django 3.0.5 on 2020-04-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0003_auto_20200404_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotestory',
            name='upVoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upvoted_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
