# Generated by Django 2.2.7 on 2020-01-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_remove_pin_upvotes'),
        ('pins', '0003_merge_20191228_2133'),
    ]

    operations = [
    ]
