# Generated by Django 2.2.6 on 2019-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_auto_20191029_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotestory',
            name='upvote',
            field=models.BooleanField(default=True),
        ),
    ]
