# Generated by Django 3.0.2 on 2020-03-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200229_1342'),
        ('pins', '0003_auto_20200305_2059'),
        ('pins', '0002_auto_20200304_0023'),
    ]

    operations = [
    ]
