# Generated by Django 2.2.6 on 2019-11-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_auto_20191105_0817'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='upvotestory',
            name='upvoter-pin',
        ),
    ]
