# Generated by Django 3.0.2 on 2020-01-29 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_auto_20200128_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pin',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
