# Generated by Django 2.2.6 on 2019-11-12 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_countupvoteflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotestory',
            name='pinId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinsUpvote', to='pins.pin'),
        ),
    ]
