# Generated by Django 3.0.2 on 2020-03-05 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0003_merge_20200305_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userStories', to=settings.AUTH_USER_MODEL),
        ),
    ]
