# Generated by Django 2.2.7 on 2020-01-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_merge_20191228_2133'),
        ('pins', '0002_auto_20200111_1854'),
    ]

    operations = [
    ]
