# Generated by Django 3.0.2 on 2020-03-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20200305_1110'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flagstory',
            constraint=models.UniqueConstraint(fields=('pinId', 'flagger'), name='flagger-pin'),
        ),
    ]
