# Generated by Django 2.2.6 on 2019-11-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20191111_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='upVotes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='countUpvoteFlag',
        ),
    ]
