# Generated by Django 2.2.6 on 2019-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_upvotestory_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotestory',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
    ]
