# Generated by Django 2.2.7 on 2020-01-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_merge_20200119_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='upVotes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
