# Generated by Django 2.2.7 on 2020-01-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_remove_pin_upvotes'),
        ('pins', '0002_auto_20191223_2133'),
        ('pins', '0004_merge_20200112_1323'),
    ]

    operations = [
    ]
