# Generated by Django 2.2.6 on 2019-10-30 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0005_remove_pin_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='categoryType',
        ),
    ]
