# Generated by Django 2.2.6 on 2019-11-14 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_auto_20191112_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotestory',
            name='upVoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updooter', to=settings.AUTH_USER_MODEL),
        ),
    ]
