# Generated by Django 2.2.7 on 2020-01-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_merge_20200118_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='upVotes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
