# Generated by Django 2.2.6 on 2019-11-05 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0005_auto_20191105_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='flagStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', models.BooleanField(default=False)),
                ('flagger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pinId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.pin')),
            ],
        ),
    ]
