# Generated by Django 3.0.2 on 2020-03-08 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_auto_20200307_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='upVotes',
        ),
        migrations.AddField(
            model_name='flagstory',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flagstory',
            name='reportType',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
