# Generated by Django 2.2.6 on 2019-11-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_auto_20191030_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.categoryType'),
        ),
    ]
