# Generated by Django 2.2.6 on 2019-11-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_auto_20191030_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='user',
        ),
    ]
