# Generated by Django 2.2.6 on 2019-11-14 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_auto_20191113_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotestory',
            name='pinId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.pin'),
        ),
        migrations.AlterField(
            model_name='upvotestory',
            name='upVoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
