# Generated by Django 2.2.7 on 2020-01-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_pin_upvotes'),
        ('pins', '0005_pin_upvotes'),
    ]

    operations = [
    ]
