# Generated by Django 3.0.2 on 2020-03-11 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0007_auto_20200309_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcomment',
            name='flagger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flaggerComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
