# Generated by Django 2.2.7 on 2019-11-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_auto_20191113_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagstory',
            name='pinId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flaggerstory', to='pins.pin'),
        ),
        migrations.AlterField(
            model_name='upvotestory',
            name='pinId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updotes', to='pins.pin'),
        ),
    ]
