# Generated by Django 2.2.6 on 2019-11-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0008_pin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
