# Generated by Django 3.0.2 on 2020-03-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0008_auto_20200311_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcomment',
            name='created',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
