# Generated by Django 3.0.2 on 2020-03-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0009_flagcomment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcomment',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
