# Generated by Django 3.0.2 on 2020-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0010_auto_20200311_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flagcomment',
            name='created',
        ),
        migrations.AddField(
            model_name='flagcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
