# Generated by Django 2.2.7 on 2020-01-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessibility_mode_active',
            field=models.BooleanField(default=False),
        ),
    ]
