# Generated by Django 3.0.4 on 2020-04-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileurl',
            field=models.URLField(null=True),
        ),
    ]
