# Generated by Django 3.0.2 on 2020-03-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200301_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'permissions': (('can_add_stories', 'Can add stories'), ('can_edit_their_stories', 'Can edit their stories'), ('can_delete_their_stories', 'Can delete their stories'), ('can_delete_other_stories', 'Can delete other user stories'), ('can_edit_other_stories', 'Can edit other user stories'), ('can_ban_users', 'Can ban users'), ('can_ban_moderators', 'Can ban moderators'), ('can_add_moderators', 'Can add moderators'), ('can_add_admin', 'Can add administrators'), ('can_add_personal_stories', 'Can add personal stories'))},
        ),
    ]
