# Generated by Django 2.2.7 on 2020-01-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200118_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_private',
            field=models.BooleanField(default=False),
        ),
    ]
