# Generated by Django 3.0.2 on 2020-01-29 05:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200118_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(null=True, upload_to=users.models.User.upload_photo_dir),
        ),
    ]
